spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homeproject?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: h0rv@thp3ter12
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
